generator/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .viewsets import PasswordViewSet, AllPasswordsViewSet
from .views import *

router = DefaultRouter()
router.register('passwords', PasswordViewSet, basename='password')
router.register('all-passwords', AllPasswordsViewSet, basename='all_passwords')

urlpatterns = [
    path('generate-passwords/', CreatePasswordView.as_view(), name='generator'),
    path('my-passwords/', PasswordListView.as_view(), name='my_passwords'),
    path('delete-password/<int:pk>/', PasswordDeleteView.as_view(), name='delete_password'),
    path('save-password/', SavePasswordView.as_view(), name='save_password'),
    path('api/', include(router.urls), )
]

users/urls.py
from django.urls import path, include
from django.views.i18n import set_language
from rest_framework.routers import DefaultRouter
from .viewsets import CustomClientViewSet, CustomAdminViewSet, AllUsersViewSet
from .views import *

router = DefaultRouter()
router.register('customers', CustomClientViewSet, basename='customer')
router.register('admins', CustomAdminViewSet, basename='admin')
router.register('all-users', AllUsersViewSet, basename='all-users')

urlpatterns = [
    path('settings/', UserSettingsView.as_view(), name='settings'),
    path('unlink-google/', unlink_oauth_google, name='unlink_google'),
    path('sign-up/', SignUpUserView.as_view(), name='sign_up'),
    path('verify-email/', VerifyEmailUserView.as_view(), name='verify_email'),
    path('resend-code/', ResendCodeView.as_view(), name="resend_code"),
    path('login/', CustomLogInView.as_view(), name='login'),
    path('logout/', CustomLogOutView.as_view(), name='logout'),
    path('delete-user/', DeleteUserView.as_view(), name='delete_user'),
    path('set-language/', set_language, name='set_language'),
    path('api/', include(router.urls))
]

generator/models.py
from django.db import models
from users.models import CustomUser


class Password(models.Model):

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='passwords')
    password = models.CharField(max_length=30)
    entropy = models.DecimalField(max_digits=10, decimal_places=2)
    decryption_years_needed = models.DecimalField(max_digits=50, decimal_places=3)
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.password}'

generator/forms.py
from django.utils.translation import gettext_lazy as _
from django import forms


class CreatePasswordForm(forms.Form):

    length_password = forms.IntegerField(
        widget=forms.TextInput(attrs={'placeholder': _('Length of the password')})
    )
    use_uppercase_letters = forms.BooleanField(
        required=False
    )
    use_digits = forms.BooleanField(
        required=False
    )
    use_punctuation_characters = forms.BooleanField(
        required=False
    )
    custom_characters_allowed = forms.CharField(
        max_length=50, required=False,
        widget=forms.TextInput(attrs={'placeholder': _('These characters will appear in the password')})
    )
    characters_not_allowed = forms.CharField(
        max_length=50, required=False,
        widget=forms.TextInput(attrs={'placeholder': _('These characters won\'t appear in the password')})
    )

    def clean(self):
        cleaned_data = super().clean()
        characters_not_allowed = self.cleaned_data.get('characters_not_allowed')
        custom_characters_allowed = self.cleaned_data.get('custom_characters_allowed')
        length_password = self.cleaned_data.get('length_password')

        if not (1 <= length_password <= 30):

            self.add_error('length_password', _('Must be between 1 to 30'))

        if characters_not_allowed:
            if any([character in custom_characters_allowed for character in characters_not_allowed]):
                self.add_error(
                    'characters_not_allowed',
                    _('A character is crashing in custom and not allowed characters')
                )

        if custom_characters_allowed:
            boolean_fields = [
                self.cleaned_data.get('use_uppercase_letters'),
                self.cleaned_data.get('use_digits'),
                self.cleaned_data.get('use_punctuation_characters')
            ]

            for situation in boolean_fields:

                if situation:

                    length_password -= 1

            if length_password <= len(set(custom_characters_allowed)):

                self.add_error(
                    'custom_characters_allowed',
                    _('There are more custom characters than available characters in the length of the password.')
                )

            return cleaned_data

generator/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import View
from django.http import Http404
from generator.utils import Generator
from django.views.generic import FormView, ListView
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CreatePasswordForm
from .models import Password


class CreatePasswordView(LoginRequiredMixin, FormView):

    template_name = 'generator.html'
    form_class = CreatePasswordForm
    success_url = reverse_lazy('generator')

    def form_valid(self, form):

        length_password = form.cleaned_data['length_password']
        use_uppercase_letters = form.cleaned_data['use_uppercase_letters']
        use_digits = form.cleaned_data['use_digits']
        use_punctuation_characters = form.cleaned_data['use_punctuation_characters']
        custom_characters_allowed = form.cleaned_data['custom_characters_allowed']
        characters_not_allowed = form.cleaned_data['characters_not_allowed']
        password = Generator.generate_password(
            length=length_password,
            use_uppercase=use_uppercase_letters,
            use_numbers=use_digits,
            use_punctuations=use_punctuation_characters,
            customized=custom_characters_allowed,
            not_allowed=characters_not_allowed
        )

        self.request.session['password'] = password
        self.request.session['password_is_new'] = True

        return super().form_valid(form)

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        if self.request.session.get('password_is_new'):
            context['password'] = self.request.session.get('password')
            self.request.session['password_is_new'] = False
        else:
            if 'password' in self.request.session:
                del self.request.session['password']

        return context


class PasswordListView(LoginRequiredMixin, ListView):

    model = Password
    template_name = 'list-passwords.html'
    context_object_name = 'passwords'
    paginate_by = 5

    def get_queryset(self):
        return Password.objects.filter(user=self.request.user).order_by('id')


class PasswordDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):

    model = Password
    template_name = 'delete_password.html'
    success_url = reverse_lazy('my_passwords')
    http_method_names = ['post']

    def test_func(self):

        password = self.get_object()
        return password.user == self.request.user


class SavePasswordView(LoginRequiredMixin, View):

    http_method_names = ['post']

    def post(self, request, *args, **kwargs):
        password = request.POST.get('password')

        if isinstance(password, str) and password:
            # Calcula métricas
            entropy = Generator.calculate_entropy(password, decimals=2)
            decryption_time = Generator.calculate_decryption_time(entropy, decimals=3)

            # Crea el registro
            Password.objects.create(
                user=request.user,
                password=password,
                entropy=entropy,
                decryption_years_needed=decryption_time
            )

            if 'password' in request.session:
                del request.session['password']

            if 'password_is_new' in request.session:
                del request.session['password_is_new']

        return redirect('my_passwords')

generator/templates/delete_password.html
{% extends 'base.html' %}

{% block head %}
    <title>Delete password</title>
{% endblock head%}

{% block body %}

{% endblock body%}

generator/templates/generator.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="{% static 'generator/css/generator.css' %}?v=1">
    <link rel="stylesheet" href="{% static 'generator/css/generate_passwords.css' %}?v=1">
    <title>
        {% trans "Generate Passwords" %}
    </title>
{% endblock head%}

{% block body %}

    <div class="form-container">
        <h2 class="content">{% trans "Generate a Password" %}</h2>

        <form method="post">
            {% csrf_token %}

            <div class="row">
                <div class="input-group">
                    <label for="id_length_password">{% trans "Length" %}:</label>
                    {{ form.length_password }}
                    {% if form.errors.length_password %}
                    <div class="length-error">
                            {{ form.errors.length_password }}
                    </div>
                    {% endif %}
                </div>

                <div class="input-group">
                    <div class="checkbox-wrapper">
                        <div class="checkbox-item">
                            <label for="id_use_uppercase_letters">{% trans "Uppercase" %}</label>
                            {{ form.use_uppercase_letters }} <span class="check-icon"></span>
                        </div>
                        <div class="checkbox-item">
                            <label for="id_use_digits">{% trans "Numbers" %}</label>
                            {{ form.use_digits }} <span class="check-icon"></span>
                        </div>
                        <div class="checkbox-item">
                            <label for="id_use_punctuation_characters">{% trans "Punctuation" %}</label>
                            {{ form.use_punctuation_characters }} <span class="check-icon"></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="full-width">
                <label for="id_custom_characters_allowed">{% trans "Custom characters allowed" %}:</label>
                {{ form.custom_characters_allowed }}
                {% if form.errors.custom_characters_allowed %}
                    <div class="error">
                        <p style="color: red ;">{{ form.errors.custom_characters_allowed }}</p>
                    </div>
                {% endif %}
            </div>

            <div class="full-width">
                <label for="id_characters_not_allowed">{% trans "Characters not allowed" %}:</label>
                {{ form.characters_not_allowed }}
                {% if form.errors.characters_not_allowed %}
                    <div class="error">
                        <p style="color: red ;">{{ form.errors.characters_not_allowed }}</p>
                    </div>
                {% endif %}
            </div>

            <div class="button-row">
                <button type="submit" class="btn-submit">{% trans "Generate a Password" %}</button>
                <a href="{% url 'my_passwords' %}" class="btn-cancel">{% trans "See my passwords" %}</a>
            </div>
        </form>
        {% if password %}
        <br/>
            <h3>{% trans "The generated password was" %}: {{ password }}</h3>
        <br/>

            <form action="{% url 'save_password' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="password" value="{{ password }}">
                <div class="button-row">
                    <button class="btn-submit" type="submit">{% trans "Save password" %}</button>
                    <a href="{% url 'generator' %}" class="btn-cancel">{% trans "Don't save" %}</a>
                </div>

            </form>

        {% endif %}
    </div>
{% endblock body %}

generator/templates/list-passwords.html
{% extends 'base.html' %}
{% load i18n %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'generator/css/list_passwords.css' %}?v=1">
    <title>
        {% trans "Generated Passwords" %}
    </title>
{% endblock head%}

{% block body %}

    <div class="table-container">
        <h3 class="content">{% trans "Generated Passwords" %}</h3>
        {% if passwords %}
            <table class="styled-table">
                <thead>
                    <tr>
                        <th>{% trans "Password" %}</th>
                        <th>{% trans "Entropy" %}</th>
                        <th>{% trans "Time to decrypt it" %}</th>
                        <th>{% trans "Generation Date" %}</th>
                        <th>{% trans "Delete Password" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for password in passwords %}
                        <tr>
                            <td>{{ password.password }}</td>
                            <td>{{ password.entropy }}</td>
                            <td>{{ password.decryption_years_needed }} {% trans "years" %}</td>
                            <td>{{ password.creation_date }}</td>
                            <td>
                                <button class="btn-center" type="button" data-bs-toggle="modal" data-bs-target="#confirmDelete{{ password.id }}">
                                    {% trans "Delete" %}
                                </button>

                                <!-- Modal de Confirmación -->
                                <div class="modal fade" id="confirmDelete{{ password.id }}" tabindex="-1" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">{% trans "Confirm deletion" %}</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                {% trans "Are you sure you want to delete the password?" %}
                                            </div>
                                            <div class="modal-footer">
                                                <form method="post" action="{% url 'delete_password' password.id %}">
                                                    {% csrf_token %}
                                                    <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
                                                </form>
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Cancel" %}</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>{% trans "You have not generated passwords yet" %}</p>
        {% endif %}
        <br>
        {% if is_paginated %}
            <div class="pagination-container">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}" class="btn-pagination">← {% trans "Previous page" %}</a>
                {% else %}
                    <span class="btn-pagination-disabled">← {% trans "Previous page" %}</span>
                {% endif %}

                <span class="pagination-info">{% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ paginator.num_pages }}</span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="btn-pagination">{% trans "Next page" %} →</a>
                {% else %}
                    <span class="btn-pagination-disabled">{% trans "Next page" %} →</span>
                {% endif %}
        {% endif %}
        </div>
        <a href="{% url 'generator' %}" class="btn-center green">{% trans "Generate a Password" %}</a>
    </div>
{% endblock body %}

generator/templates/save_password.html
{% extends 'base.html' %}

{% block head %}
    <title>Title</title>
{% endblock head %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit"></button>
    </form>
{% endblock body %}